### ISSUE TITLE
The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by wmmc88** [ruffsl/colcon-clean#10]
```
❯ colcon clean workspace
Paths:
     build
     log
Clean the above paths? [Y/n] Y
[2.517s] colcon ERROR colcon clean: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\melvi\\git-repos\\ros2_uwrt_ws\\log\\clean_2021-12-24_19-14-23\\logger_all.log'
Traceback (most recent call last):
  File "C:\python38\lib\site-packages\colcon_core\command.py", line 528, in verb_main
    rc = context.args.main(context=context)
  File "C:\python38\lib\site-packages\colcon_clean\subverb\workspace.py", line 58, in main
    clean_paths(
  File "C:\python38\lib\site-packages\colcon_clean\subverb\__init__.py", line 242, in clean_paths
    _clean_path(path)
  File "C:\python38\lib\site-packages\colcon_clean\subverb\__init__.py", line 249, in _clean_path
    shutil.rmtree(path)
  File "C:\python38\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\python38\lib\shutil.py", line 613, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\python38\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\python38\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\melvi\\git-repos\\ros2_uwrt_ws\\log\\clean_2021-12-24_19-14-23\\logger_all.log'
```

This behaviour is on Windows. I think this is caused because its attempting to remove the log dir when invoking a colcon command writes to the log dir. This doesn't happen when specifying non-log folders using `--base-select build` or similar.

**Comment by ruffsl** [comment]
Interesting, definitely sounds like a race condition. Any idea why this effects only windows? I don't recall encountering this issue on Linux, as cleaning the workspace on Linux merely results in a remaining log file for from clean task that is written to disk after completing the deletion of the prior log directory.

**Comment by wmmc88** [comment]
I'm guessing because whatever posix apis `shutil.rmtree` calls will handle when a file is being used in the folder that is "to be deleted" but the windows apis dont?

**Comment by ruffsl** [comment]
Ok, so one thing we could do is to simply pass `ignore_errors=True` to `shutil.rmtree`, like so:

https://github.com/ruffsl/colcon-clean/blob/65f9be369b396c13e604a9272a5ed4fe77895700/colcon_clean/subverb/__init__.py#L249

``` diff
-        shutil.rmtree(path)
+        shutil.rmtree(path, ignore_errors=True)
```

https://docs.python.org/3/library/shutil.html#shutil.rmtree

This would insure consistent behavior across linux and windows, while retaining the present behavior of preserving the colcon clean logs.  Of course, this has the negative side effect of ignoring any other errors, some which may be still be of significance to the user.

Alternatively, an `onerror` callback could be passed instead, allowing for skipped paths to be logged as well:

``` python
def _onerror(func, path, excinfo):
    print('LOL ERROR: ', str(excinfo[1]))
    if excinfo[0] == PermissionError:
        logger.info(
            "Skipping path: '{path}'".format_map(locals()))
        return
    raise

def _clean_path(path):
    logger.info(
        "Cleaning path: '{path}'".format_map(locals()))
    if path.is_dir():
        shutil.rmtree(path, onerror=_onerror)
    else:
        path.unlink()
```

However, this alone does not then guard agents errors due to now non-empty directories. Given how `rmtree` reclusively walks the file tree structure, it assumes all child files have been deleted by the time it then attempts to delete the parent folder.

<details>

```
> colcon clean workspace
Paths:
     build
     log
Clean the above paths? [Y/n] Y
OLD ERROR:  [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ruffsl\\ws\\test\\log\\clean_2021-12-25_17-18-37\\logger_all.log'
NEW ERROR:  [WinError 145] The directory is not empty: 'C:\\Users\\ruffsl\\ws\\test\\log\\clean_2021-12-25_17-18-37'
[2.044s] colcon ERROR colcon clean: [WinError 145] The directory is not empty: 'C:\\Users\\ruffsl\\ws\\test\\log\\clean_2021-12-25_17-18-37'
Traceback (most recent call last):
  File "C:\Users\ruffsl\AppData\Roaming\Python\Python38\site-packages\colcon_core\command.py", line 528, in verb_main
    rc = context.args.main(context=context)
  File "C:\Users\ruffsl\ws\colcon\build\colcon-clean\colcon_clean\subverb\workspace.py", line 58, in main
    clean_paths(
  File "C:\Users\ruffsl\ws\colcon\build\colcon-clean\colcon_clean\subverb\__init__.py", line 242, in clean_paths
    _clean_path(path)
  File "C:\Users\ruffsl\ws\colcon\build\colcon-clean\colcon_clean\subverb\__init__.py", line 256, in _clean_path
    shutil.rmtree(path, onerror=_onerror)
  File "c:\python38\lib\shutil.py", line 737, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\python38\lib\shutil.py", line 610, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\python38\lib\shutil.py", line 619, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "c:\python38\lib\shutil.py", line 617, in _rmtree_unsafe
    os.rmdir(path)
OSError: [WinError 145] The directory is not empty: 'C:\\Users\\ruffsl\\ws\\test\\log\\clean_2021-12-25_17-18-37'
``` 

</details>

The new raised error seems to be generic while also OS specific, so not very clean to catch.

Any suggestions?

**Comment by wmmc88** [comment]
Probably the simplest sufficient approach is to:
1. call `shutil.rmtree(path)` 
2. catch errors, print warnings about errors caught, call `shutil.rmtree(path, ignore_errors=True)`

This way its transparent to the user that errors occurred, but still basically completes the core job of `colcon-clean`. Also maintains current behaviour of keeping logs of clean command.

You could maybe also change the logic to detect the folder that colcon is creating when logging the clean command, then explictly call rmtree on all the subfolders of the `log` folder _expcept_ for the folder used for logging the clean command.

**Comment by ruffsl** [comment]
> Probably the simplest sufficient approach is to:

While simple, I think that approach would only give one warning per invocation, i.e. for the first encountered problematic file found while walking back up the directory tree. A second invocation of `rmtree` with `ignore_errors=True` would inadvertently silence subsequent problematic files under the same path. So I think it would me more intuitive for the CLI to warn about all problematic files in one go, not just the first.

> You could maybe also change the logic to detect the folder that colcon is creating when logging the clean command

I'd like to keep the clean path logic agnostic of any base path specifics or quirks, as the logic behind base paths are extensions themselves, so folks could add other base path types if desired.

**Comment by wmmc88** [comment]
thanks @ruffsl! Can confirm that the fix is working as expected :)
