### ISSUE TITLE
Plan to release

### ISSUE THREAD

**Issue by ejalaa12** [ruffsl/colcon-clean#31]
Hi, 
Unless mistaken, this colcon verb is not released with apt.
It is a very handy extension, are there any plans to release it?

**Comment by ruffsl** [comment]
Indeed we do plan on releasing this extension as so to be apt installable. @cottsay , are there any last blockers?

**Comment by cottsay** [comment]
> are there any last blockers?

I'm not tracking anything.

@ruffsl, you'll need privileges on https://packagecloud.io/dirk-thomas/colcon. Right now, only @dirk-thomas has the ability to do that.

For now, can you push and tag a release in this repository, and I'll handle building the deb and pushing to PyPI?

**Comment by ejalaa12** [comment]
That's awesome, thanks :)

**Comment by ruffsl** [comment]
> For now, can you push and tag a release in this repository, and I'll handle building the deb and pushing to PyPI?

@cottsay , please see https://github.com/colcon/colcon-clean/releases/tag/0.2.0

**Comment by cottsay** [comment]
:ship: https://pypi.org/project/colcon-clean/0.2.0/

**Comment by cottsay** [comment]
@ruffsl, do you have a PyPI account? If so, I can add access for you to make releases of this package. Just shoot me a link to your profile.

**Comment by ruffsl** [comment]
@cottsay , thought I had one before, but found that was just for an old org/project.
I just created one for my current user handle: https://pypi.org/user/ruffsl/

**Comment by cottsay** [comment]
> I just created one for my current user handle

Looks great, invite sent. Please make sure you have 2FA enabled.

**Comment by ejalaa12** [comment]
Thanks for your reactivity!
