### ISSUE TITLE
Does not pick up on colcon configuration file.

### ISSUE THREAD

**Issue by artivis** [ruffsl/colcon-clean#42]
`colcon-clean` does not seem to be picking up on existing colcon configuration file.
Given `~/.colcon/defaults.yaml` as:

```yaml
{
  "build": {"build-base": "/home/ubuntu/colcon-build"}
}
```

commands such as `colcon clean workspace --base-select build` still propose the default `build` rather than the configured default `/home/ubuntu/colcon-build`.

**Comment by cottsay** [comment]
The first-level key in a colcon defaults file isn't a semantic class of operations to associate the arguments with, it is a literal verb (as in the thing that immediately follows `colcon` in your commands).

To change the `build-base` for `colcon-clean`, you should have entries like this:
```json
{
  "clean.packages": {"build-base": "/home/ubuntu/colcon-build"},
  "clean.workspace": {"build-base": "/home/ubuntu/colcon-build"}
}
```

**Comment by artivis** [comment]
Right, that makes sense. Thanks @cottsay :+1: .
